class Data{
    constructor(){
        this.d= new Date(),
        this.months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        this.homepageLink = "https://auct-app2-frontend.herokuapp.com/",
        this.EC = protractor.ExpectedConditions,
        this.headerText= ".header-text",
        this.emailLocator = "#email",
        this.userRafaNadal = "rafa@mail.com",
        this.dataWithEmptySpaces = "     ",
        this.passwordUserRafaNadal ="password",
        this.categoryItemLocator=".category-item",
        this.landingProductLocator=".landing-product",
        this.bidForSmokeTest=1003,
        this.bidWithDecimalPlaces=400.25,
        this.higherBid = 5000,
        this.biderNameImgLocator=".bider-name-img",
        this.userAssert ="Rafa Nadal",
        this.bidAssert="$1003.00",
        this.higherBidAssert = "$5000.00",
        this.BidWithDecimlPlacesAssert="$400.25.00",
        this.itemDetailsAssert="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
        this.statusSuccessLocator=".status-success",
        this.formTitleLocator = ".form-title",
        this.haveAccountLocator = ".have-account",
        this.helperLocator = ".helper",
        this.statusInfoLocator = ".status-info",
        this.highestBidderMessage="Congrats! you are the higest bider!",
        this.successfullRegistrationMessage="You are registered! Login here",
        this.unsuccessfullRegstrationMessage="User with given email already exists",
        this.firstNameValidationMessage = "First Name is required",
        this.lastNameValidationMessage ="Last Name is required",
        this.invalidEmailMessage = "Invalid email",
        this.invalidPasswordMessage ="Password must be longer than 5 letters",
        this.invalidConfirmPasswordMessage = "Password is not matching",
        this.registerURLAssertion = "https://auct-app2-frontend.herokuapp.com/register",
        this.loginValidationMessage = "Invalid username or password",
        this.lowerBidThanStartingPriceMessage = "There are higher bids than yours. You could give a second try!",
        this.aboutUsAssert = "About Us",
        this.introductionAssert = "Introduction",
        this.someTitleHereAssert = "Some title here",
        this.invalidDollarCharacter = "$",
        this.invalidPasswordCharacters = "%%%%%"
    }
}
module.exports = new Data();